### ISSUE TITLE
iOS:  Crash Check Overlap -> Check Public Data

### ISSUE THREAD

**Issue by craig-miller** [tripleblindmarket/private-kit#205]
iOS 13.3.1
iPhone 11 Pro Max MWFM2LL/A

Expected:  Not sure, I haven't seen the spec for Check Overlap
Actual Behavior:  Crash

Test Flight version 0.5.8 (13)
Opened App by pressing Open button inside of TestFlight
Started logging Previously, so I'm seeing the "Stop Logging" and "Check Overlap" buttons.
Click Check Overlap
Click Check Public Data
loading data... appears (Not that this should be uppercase "Loading Data..."
A few seconds elapse
App crashes hard

**Comment by rparet** [comment]
Fixed in #212

**Comment by carverofchoice** [comment]
This isn't fixed. I'm currently (4/4/2020 4:30pm MST) having this problem with a Note 8 and Android 9

From the Private Kit Licenses Screen:
Private Kit
Version 0.5.11
OS: android v28
Screen Resolution: 411X845

Device: Samsung Galaxy Note 8
Model: SM-N950U
Android 9
Sprint

Weeks ago I imported my google GPS data. It worked fine until the latest update (changing from green circles and red location markers to showing people as location markers). 

Now when I 
1) click "Check Overlap" and then 
2) click "Click to view the public dataset" 
Expected Result: Show red circles of reported infection zones (this is what it did before the update)
Actual Result: it crashes, every time. Since at least 4/2/2020.

Tried force-stop and reload. Tried rebooting phone. 

Attached a video:
[Video of crashing.zip](https://github.com/tripleblindmarket/private-kit/files/4432639/Video.of.crashing.zip)
